"use strict";

/**
 * Deploy: on Vercel (VERCEL=1), writes auth-config.js when JB_SUPABASE_URL + JB_SUPABASE_ANON_KEY exist.
 * Local: same only if JB_WRITE_AUTH_CONFIG=1 (optional .env / .env.local loaded first).
 *
 * Env files (optional, keys do not override already-set process.env):
 *   .env, .env.local, .env.production, .env.production.local
 */

var fs = require("fs");
var path = require("path");

var root = path.join(__dirname, "..");
var target = path.join(root, "auth-config.js");

function loadDotEnv(rel) {
  var fp = path.join(root, rel);
  if (!fs.existsSync(fp)) return;
  var text = fs.readFileSync(fp, "utf8");
  text.split(/\r?\n/).forEach(function (line) {
    line = line.replace(/^\uFEFF/, "").trim();
    if (!line || line.charAt(0) === "#") return;
    var eq = line.indexOf("=");
    if (eq <= 0) return;
    var k = line.slice(0, eq).trim();
    var v = line.slice(eq + 1).trim();
    if (
      (v.charAt(0) === '"' && v.charAt(v.length - 1) === '"') ||
      (v.charAt(0) === "'" && v.charAt(v.length - 1) === "'")
    ) {
      v = v.slice(1, -1);
    }
    if (process.env[k] === undefined) process.env[k] = v;
  });
}

[".env", ".env.local", ".env.production", ".env.production.local"].forEach(loadDotEnv);

var url = String(process.env.JB_SUPABASE_URL || "").trim();
var key = String(process.env.JB_SUPABASE_ANON_KEY || "").trim();
var domain = String(process.env.JB_SYNTHETIC_EMAIL_DOMAIN || "jbphonelogin.local").trim();
var mode = String(process.env.JB_STORAGE_MODE || "").trim().toLowerCase();

var onVercel = process.env.VERCEL === "1";
var forceLocalWrite = String(process.env.JB_WRITE_AUTH_CONFIG || "").trim() === "1";

if (!url || !key) {
  console.log(
    "[jbmanager] JB_SUPABASE_URL / JB_SUPABASE_ANON_KEY missing; keeping auth-config.js as in repo."
  );
  process.exit(0);
}

if (!onVercel && !forceLocalWrite) {
  console.log(
    "[jbmanager] Supabase env present but not on Vercel. Set JB_WRITE_AUTH_CONFIG=1 to rewrite auth-config.js locally, or deploy on Vercel."
  );
  process.exit(0);
}

if (!mode || (mode !== "supabase" && mode !== "local")) {
  mode = "supabase";
}

var contents =
  "/**\n" +
  " * Generated by scripts/vercel-build.js — do not edit in deployed artifacts.\n" +
  " */\n" +
  "window.JBAuthConfig = {\n" +
  "  storageMode: " +
  JSON.stringify(mode) +
  ",\n" +
  "  apiBaseUrl: \"\",\n" +
  "  supabaseUrl: " +
  JSON.stringify(url) +
  ",\n" +
  "  supabaseAnonKey: " +
  JSON.stringify(key) +
  ",\n" +
  "  syntheticEmailDomain: " +
  JSON.stringify(domain) +
  ",\n" +
  "};\n";

fs.writeFileSync(target, contents, "utf8");
console.log("[jbmanager] auth-config.js written (storageMode=" + mode + ").");
